import { QuoteItem } from "./types";

/* Task 40-i18n-ru — every quote now carries optional RU fields:
 *   ru / authorRu  → ready Russian text (consume as `q.ru ?? q.en`)
 *   ruX / ruY      → Russian subject words for the generator; ALSO mirrored
 *                    on base quotes (ruX === ru) so a `q.ruX ?? q.en` lookup
 *                    lands on Russian there too.
 * NOTE: per-language quote SELECTION happens in App.tsx (library quote card,
 * `lang === "fa" ? q.fa : lang === "tr" ? q.tr : q.en`) — that file belongs to
 * another agent. When wiring ru there, use `(trackQuote.ru ?? trackQuote.en)`.
 */
const BASE_QUOTES: QuoteItem[] = [
  {
    id: 1,
    fa: "موسیقی‌هایی که شب را تغییر می‌دهند.",
    en: "Music that transforms the night.",
    tr: "Geceyi değiştiren müzikler.",
    ru: "Музыка, которая меняет ночь.",
    ruX: "Музыка, которая меняет ночь.",
    authorFa: "NOBODY ARCHIVE",
    authorEn: "NOBODY ARCHIVE",
    authorTr: "NOBODY ARCHIVE",
    authorRu: "NOBODY ARCHIVE",
  },
  {
    id: 2,
    fa: "جایی که کلمات ناکام می‌مانند، موسیقی آغاز به سخن می‌کند.",
    en: "Where words fail, music speaks.",
    tr: "Kelimelerin yetersiz kaldığı yerde müzik konuşur.",
    ru: "Там, где слова бессильны, говорит музыка.",
    ruX: "Там, где слова бессильны, говорит музыка.",
    authorFa: "هانس کریستیان اندرسن",
    authorEn: "Hans Christian Andersen",
    authorTr: "Hans Christian Andersen",
    authorRu: "Ханс Кристиан Андерсен",
  },
  {
    id: 3,
    fa: "بدون موسیقی، زندگی یک اشتباه می‌بود.",
    en: "Without music, life would be a mistake.",
    tr: "Müziksiz bir hayat bir hata olurdu.",
    ru: "Без музыки жизнь была бы ошибкой.",
    ruX: "Без музыки жизнь была бы ошибкой.",
    authorFa: "فریدریش نیچه",
    authorEn: "Friedrich Nietzsche",
    authorTr: "Friedrich Nietzsche",
    authorRu: "Фридрих Ницше",
  },
  {
    id: 4,
    fa: "موسیقی پناهگاهی است برای ارواحی که در سکوت شب بیدارند.",
    en: "Music is a sanctuary for souls awake in the silence of the night.",
    tr: "Müzik, gecenin sessizliğinde uyanık kalan ruhlar için bir sığınaktır.",
    ru: "Музыка — пристанище для душ, которые бодрствуют в ночной тишине.",
    ruX: "Музыка — пристанище для душ, которые бодрствуют в ночной тишине.",
    authorFa: "EPODONIOS",
    authorEn: "EPODONIOS",
    authorTr: "EPODONIOS",
    authorRu: "EPODONIOS",
  },
  {
    id: 5,
    fa: "یک قطعه موسیقی، کلید قفل‌گشایی خاطرات فراموش‌شده است.",
    en: "A piece of music is the key to unlocking forgotten memories.",
    tr: "Bir müzik parçası, unutulmuş anıları açan bir anahtardır.",
    ru: "Музыкальная пьеса — ключ, отпирающий забытые воспоминания.",
    ruX: "Музыкальная пьеса — ключ, отпирающий забытые воспоминания.",
    authorFa: "یوهان سباستیان باخ",
    authorEn: "Johann Sebastian Bach",
    authorTr: "Johann Sebastian Bach",
    authorRu: "Иоганн Себастьян Бах",
  },
  {
    id: 6,
    fa: "شب با نت‌های ملایم، تاریکی را به آرامش تبدیل می‌کند.",
    en: "The night turns darkness into solace with gentle notes.",
    tr: "Gece, yumuşak notalarla karanlığı huzura dönüştürür.",
    ru: "Ночь мягкими нотами превращает тьму в утешение.",
    ruX: "Ночь мягкими нотами превращает тьму в утешение.",
    authorFa: "شوpen",
    authorEn: "Frédéric Chopin",
    authorTr: "Frédéric Chopin",
    authorRu: "Фредерик Шопен",
  },
  {
    id: 7,
    fa: "موسیقی، زبان جهانی احساساتی است که مرزی نمی‌شناسند.",
    en: "Music is the universal language of emotions without borders.",
    tr: "Müzik, sınırı olmayan duyguların evrensel dilidir.",
    ru: "Музыка — универсальный язык чувств, не знающих границ.",
    ruX: "Музыка — универсальный язык чувств, не знающих границ.",
    authorFa: "لودویگ وان بتهوون",
    authorEn: "Ludwig van Beethoven",
    authorTr: "Ludwig van Beethoven",
    authorRu: "Людвиг ван Бетховен",
  },
  {
    id: 8,
    fa: "هر ملودی، قصه ناگفته‌ای است از قلبی که می‌تپد.",
    en: "Every melody is an untold story of a beating heart.",
    tr: "Her melodi, atan bir kalbin anlatılmamış hikayesidir.",
    ru: "Каждая мелодия — нерассказанная история бьющегося сердца.",
    ruX: "Каждая мелодия — нерассказанная история бьющегося сердца.",
    authorFa: "EPODONIOS",
    authorEn: "EPODONIOS",
    authorTr: "EPODONIOS",
    authorRu: "EPODONIOS",
  },
  {
    id: 9,
    fa: "وقتی همه خوابند، موسیقی همدمی برای افکار عمیق ماست.",
    en: "When all are asleep, music is a companion to our deepest thoughts.",
    tr: "Herkes uyurken müzik, en derin düşüncelerimizin yoldaşıdır.",
    ru: "Когда все спят, музыка становится собеседником наших самых глубоких мыслей.",
    ruX: "Когда все спят, музыка становится собеседником наших самых глубоких мыслей.",
    authorFa: "کلود دبوسی",
    authorEn: "Claude Debussy",
    authorTr: "Claude Debussy",
    authorRu: "Клод Дебюсси",
  },
  {
    id: 10,
    fa: "صداهای شبانه، ارتعاش خاموش جهان را آشکار می‌کنند.",
    en: "Night sounds reveal the silent vibration of the universe.",
    tr: "Gece sesleri, evrenin sessiz titreşimini açığa çıkarır.",
    ru: "Ночные звуки открывают беззвучную вибрацию вселенной.",
    ruX: "Ночные звуки открывают беззвучную вибрацию вселенной.",
    authorFa: "اریک сати",
    authorEn: "Erik Satie",
    authorTr: "Erik Satie",
    authorRu: "Эрик Сати",
  },
  {
    id: 11,
    fa: "موسیقی، استراحتی است برای ذهنی که از شلوغی روز خسته است.",
    en: "Music is a rest for the mind tired of the day's clamor.",
    tr: "Müzik, günün gürültüsünden yorulmuş zihnin dinlenmesidir.",
    ru: "Музыка — отдых для ума, уставшего от дневной суеты.",
    ruX: "Музыка — отдых для ума, уставшего от дневной суеты.",
    authorFa: "یوهانس برامس",
    authorEn: "Johannes Brahms",
    authorTr: "Johannes Brahms",
    authorRu: "Иоганнес Брамс",
  },
  {
    id: 12,
    fa: "ریتم موسیقی قلب شما را با نبض زمین هماهنگ می‌کند.",
    en: "The rhythm of music synchronizes your heart with the pulse of the earth.",
    tr: "Müziğin ritmi, kalbinizi dünyanın nabzıyla senkronize eder.",
    ru: "Ритм музыки синхронизирует твоё сердце с пульсом Земли.",
    ruX: "Ритм музыки синхронизирует твоё сердце с пульсом Земли.",
    authorFa: "EPODONIOS",
    authorEn: "EPODONIOS",
    authorTr: "EPODONIOS",
    authorRu: "EPODONIOS",
  },
  {
    id: 13,
    fa: "بهترین موسیقی، آن است که بعد از پایان هم در سکوت شنیده شود.",
    en: "The best music is what is heard in silence even after it ends.",
    tr: "En iyi müzik, bittikten sonra bile sessizlikte duyulandır.",
    ru: "Лучшая музыка — та, что и после конца продолжает звучать в тишине.",
    ruX: "Лучшая музыка — та, что и после конца продолжает звучать в тишине.",
    authorFa: "ولفگانگ آمادئوس موتزارت",
    authorEn: "Wolfgang Amadeus Mozart",
    authorTr: "Wolfgang Amadeus Mozart",
    authorRu: "Вольфганг Амадей Моцарт",
  },
  {
    id: 14,
    fa: "در تاریکی شب، هیچ نوری درخشان‌تر از یک آهنگ مورد علاقه نیست.",
    en: "In the dark of night, no light shines brighter than a favorite song.",
    tr: "Gecenin karanlığında, favori bir şarkıdan daha parlak bir ışık yoktur.",
    ru: "В ночной тьме нет света ярче любимой песни.",
    ruX: "В ночной тьме нет света ярче любимой песни.",
    authorFa: "EPODONIOS",
    authorEn: "EPODONIOS",
    authorTr: "EPODONIOS",
    authorRu: "EPODONIOS",
  },
  {
    id: 15,
    fa: "موسیقی عالی، پرواز روح از قفس کلمات است.",
    en: "Great music is the soul's flight from the cage of words.",
    tr: "Harika müzik, ruhun kelime kafesinden uçuşudur.",
    ru: "Великая музыка — полёт души из клетки слов.",
    ruX: "Великая музыка — полёт души из клетки слов.",
    authorFa: "ویکتور هوگو",
    authorEn: "Victor Hugo",
    authorTr: "Victor Hugo",
    authorRu: "Виктор Гюго",
  },
  {
    id: 16,
    fa: "هر آهنگ یک کپسول زمان است که لحظه‌ها را جاودانه می‌کند.",
    en: "Every song is a time capsule making moments immortal.",
    tr: "Her şarkı, anları ölümsüz kılan bir zaman kapsülüdür.",
    ru: "Каждая песня — капсула времени, делающая мгновения бессмертными.",
    ruX: "Каждая песня — капсула времени, делающая мгновения бессмертными.",
    authorFa: "EPODONIOS",
    authorEn: "EPODONIOS",
    authorTr: "EPODONIOS",
    authorRu: "EPODONIOS",
  },
  {
    id: 17,
    fa: "در سکوت نیمه‌شب، نت‌ها با وضوحی کریستالی به گوش می‌رسند.",
    en: "In midnight silence, notes are heard with crystal clarity.",
    tr: "Gece yarısı sessizliğinde, notalar kristal netliğinde duyulur.",
    ru: "В полночной тишине ноты слышны с кристальной чистотой.",
    ruX: "В полночной тишине ноты слышны с кристальной чистотой.",
    authorFa: "پیوتر ایلیچ چایکوفسکی",
    authorEn: "Pyotr Ilyich Tchaikovsky",
    authorTr: "Pyotr Ilyich Tchaikovsky",
    authorRu: "Пётр Ильич Чайковский",
  },
  {
    id: 18,
    fa: "موسیقی تنها هنری است که بی‌واسطه قلب را لمس می‌کند.",
    en: "Music is the only art that touches the heart without intermediary.",
    tr: "Müzik, kalbe aracısız dokunan tek sanattır.",
    ru: "Музыка — единственное искусство, касающееся сердца напрямую.",
    ruX: "Музыка — единственное искусство, касающееся сердца напрямую.",
    authorFa: "آرتور شوپنهاور",
    authorEn: "Arthur Schopenhauer",
    authorTr: "Arthur Schopenhauer",
    authorRu: "Артур Шопенгауэр",
  },
  {
    id: 19,
    fa: "وقتی گوش می‌دهی، تمام کهکشان در رگ‌هایت می‌تپد.",
    en: "When you listen, the entire galaxy beats in your veins.",
    tr: "Dinlediğinde, bütün galaksi damarlarında atar.",
    ru: "Когда слушаешь, вся галактика пульсирует в твоих венах.",
    ruX: "Когда слушаешь, вся галактика пульсирует в твоих венах.",
    authorFa: "EPODONIOS",
    authorEn: "EPODONIOS",
    authorTr: "EPODONIOS",
    authorRu: "EPODONIOS",
  },
  {
    id: 20,
    fa: "زیبایی شب در این است که تنها صدای موسیقی باقی می‌ماند.",
    en: "The beauty of the night is that only the sound of music remains.",
    tr: "Gecenin güzelliği, sadece müziğin sesinin kalmasıdır.",
    ru: "Красота ночи в том, что остаётся только звук музыки.",
    ruX: "Красота ночи в том, что остаётся только звук музыки.",
    authorFa: "سرگئی راخمانینف",
    authorEn: "Sergei Rachmaninoff",
    authorTr: "Sergei Rachmaninoff",
    authorRu: "Сергей Рахманинов",
  },
  {
    id: 21,
    fa: "موسیقی، معماری سیال صداها در فضای زمان است.",
    en: "Music is the fluid architecture of sounds in the space of time.",
    tr: "Müzik, zaman uzayında seslerin akıcı mimarisidir.",
    ru: "Музыка — текучая архитектура звуков в пространстве времени.",
    ruX: "Музыка — текучая архитектура звуков в пространстве времени.",
    authorFa: "یوهان ولفگانگ فون گوته",
    authorEn: "Johann Wolfgang von Goethe",
    authorTr: "Johann Wolfgang von Goethe",
    authorRu: "Иоганн Вольфганг фон Гёте",
  },
  {
    id: 22,
    fa: "با هر ترانه، بخشی از روحمان را بازمی‌یابیم.",
    en: "With every song, we rediscover a piece of our soul.",
    tr: "Her şarkıyla ruhumuzun bir parçasını yeniden keşfederiz.",
    ru: "С каждой песней мы вновь обретаем частицу своей души.",
    ruX: "С каждой песней мы вновь обретаем частицу своей души.",
    authorFa: "EPODONIOS",
    authorEn: "EPODONIOS",
    authorTr: "EPODONIOS",
    authorRu: "EPODONIOS",
  },
  {
    id: 23,
    fa: "موسیقی، هوای تازه برای روحی است که در روزمرگی حبس شده است.",
    en: "Music is fresh air for a soul trapped in routine.",
    tr: "Müzik, rutine hapsolmuş bir ruh için taze havadır.",
    ru: "Музыка — глоток свежего воздуха для души, запертой в повседневности.",
    ruX: "Музыка — глоток свежего воздуха для души, запертой в повседневности.",
    authorFa: "ایگور استراوینسکی",
    authorEn: "Igor Stravinsky",
    authorTr: "Igor Stravinsky",
    authorRu: "Игорь Стравинский",
  },
  {
    id: 24,
    fa: "در شب‌های بارانی، موسیقی بوی خاک باران‌خورده را دارد.",
    en: "On rainy nights, music holds the scent of wet earth.",
    tr: "Yağmurlu gecelerde müzik, ıslak toprak kokusunu taşır.",
    ru: "Дождливыми ночами музыка пахнет мокрой землёй.",
    ruX: "Дождливыми ночами музыка пахнет мокрой землёй.",
    authorFa: "EPODONIOS",
    authorEn: "EPODONIOS",
    authorTr: "EPODONIOS",
    authorRu: "EPODONIOS",
  },
  {
    id: 25,
    fa: "صداهای خوب، مرهمی بر زخم‌های نادیده هستند.",
    en: "Good sounds are a salve for unseen wounds.",
    tr: "Güzel sesler, görünmeyen yaralara bir merhemdir.",
    ru: "Хорошие звуки — бальзам на невидимые раны.",
    ruX: "Хорошие звуки — бальзам на невидимые раны.",
    authorFa: "گوستاو مالر",
    authorEn: "Gustav Mahler",
    authorTr: "Gustav Mahler",
    authorRu: "Густав Малер",
  },
  {
    id: 26,
    fa: "شب، بوم نقاشی تاریکی است که موسیقی آن را رنگ‌آمیزی می‌کند.",
    en: "The night is a dark canvas that music paints with color.",
    tr: "Gece, müziğin renklendirdiği karanlık bir tuvaldir.",
    ru: "Ночь — тёмный холст, который раскрашивает музыка.",
    ruX: "Ночь — тёмный холст, который раскрашивает музыка.",
    authorFa: "EPODONIOS",
    authorEn: "EPODONIOS",
    authorTr: "EPODONIOS",
    authorRu: "EPODONIOS",
  },
  {
    id: 27,
    fa: "نت‌ها هرگز دروغ نمی‌گویند؛ آن‌ها حقیقت احساس را نشان می‌دهند.",
    en: "Notes never lie; they reveal the truth of emotion.",
    tr: "Notalar asla yalan söylemez; duygunun gerçeğini gösterir.",
    ru: "Ноты никогда не лгут — они являют правду чувства.",
    ruX: "Ноты никогда не лгут — они являют правду чувства.",
    authorFa: "لئونارد برنستاین",
    authorEn: "Leonard Bernstein",
    authorTr: "Leonard Bernstein",
    authorRu: "Леонард Бернстайн",
  },
  {
    id: 28,
    fa: "در میان همهمه جهان، موسیقی جزیره آرامش شماست.",
    en: "Amidst the world's chaos, music is your island of calm.",
    tr: "Dünyanın kaosunun ortasında müzik, sizin huzur adanızdır.",
    ru: "Среди мирового хаоса музыка — твой остров покоя.",
    ruX: "Среди мирового хаоса музыка — твой остров покоя.",
    authorFa: "EPODONIOS",
    authorEn: "EPODONIOS",
    authorTr: "EPODONIOS",
    authorRu: "EPODONIOS",
  },
  {
    id: 29,
    fa: "هر ملودی، دریچه‌ای است به ابدیتی که در درون ماست.",
    en: "Every melody is a portal to the eternity within us.",
    tr: "Her melodi, içimizdeki sonsuzluğa açılan bir kapıdır.",
    ru: "Каждая мелодия — врата в вечность внутри нас.",
    ruX: "Каждая мелодия — врата в вечность внутри нас.",
    authorFa: "آنتونیو ویوالدی",
    authorEn: "Antonio Vivaldi",
    authorTr: "Antonio Vivaldi",
    authorRu: "Антонио Вивальди",
  },
  {
    id: 30,
    fa: "وقتی ریتم آغاز می‌شود، مرزهای زمان فرومی‌ریزند.",
    en: "When the rhythm begins, the borders of time collapse.",
    tr: "Ritim başladığında zamanın sınırları yıkılır.",
    ru: "Когда начинается ритм, границы времени рушатся.",
    ruX: "Когда начинается ритм, границы времени рушатся.",
    authorFa: "EPODONIOS",
    authorEn: "EPODONIOS",
    authorTr: "EPODONIOS",
    authorRu: "EPODONIOS",
  },
  {
    id: 31,
    fa: "موسیقی، آتش‌گردانی است که در شب‌های سرد دل را گرم می‌کند.",
    en: "Music is a fire that warms the heart on cold nights.",
    tr: "Müzik, soğuk gecelerde kalbi ısıtan bir ateştir.",
    ru: "Музыка — огонь, что греет сердце в холодные ночи.",
    ruX: "Музыка — огонь, что греет сердце в холодные ночи.",
    authorFa: "فرانتس شوبرت",
    authorEn: "Franz Schubert",
    authorTr: "Franz Schubert",
    authorRu: "Франц Шуберт",
  },
  {
    id: 32,
    fa: "هیچ‌کس در حضور موسیقی عمیق، تنها نیست.",
    en: "Nobody is alone in the presence of deep music.",
    tr: "Derin müziğin varlığında hiç kimse yalnız değildir.",
    ru: "Никто не одинок рядом с глубокой музыкой.",
    ruX: "Никто не одинок рядом с глубокой музыкой.",
    authorFa: "EPODONIOS",
    authorEn: "EPODONIOS",
    authorTr: "EPODONIOS",
    authorRu: "EPODONIOS",
  },
  {
    id: 33,
    fa: "صدا، قوی‌ترین پل میان انسان‌ها در طول قرن‌هاست.",
    en: "Sound is the strongest bridge between humans across centuries.",
    tr: "Ses, yüzyıllar boyunca insanlar arasındaki en güçlü köprüdür.",
    ru: "Звук — самый крепкий мост между людьми сквозь века.",
    ruX: "Звук — самый крепкий мост между людьми сквозь века.",
    authorFa: "ربرت شومان",
    authorEn: "Robert Schumann",
    authorTr: "Robert Schumann",
    authorRu: "Роберт Шуман",
  },
  {
    id: 34,
    fa: "گوش دادن عمیق، یک سفر مراقبه به ژرفای درون است.",
    en: "Deep listening is a meditative journey into the depths within.",
    tr: "Derinlemesine dinlemek, içsel derinliklere yapılan meditatif bir yolculuktur.",
    ru: "Глубокое слушание — медитативное путешествие в собственные глубины.",
    ruX: "Глубокое слушание — медитативное путешествие в собственные глубины.",
    authorFa: "فیلپ گلس",
    authorEn: "Philip Glass",
    authorTr: "Philip Glass",
    authorRu: "Филип Гласс",
  },
  {
    id: 35,
    fa: "موسیقی شبانه، سایه‌ها را به رقص درمی‌آورد.",
    en: "Nocturnal music makes the shadows dance.",
    tr: "Gece müziği gölgeleri dans ettirir.",
    ru: "Ночная музыка заставляет тени танцевать.",
    ruX: "Ночная музыка заставляет тени танцевать.",
    authorFa: "EPODONIOS",
    authorEn: "EPODONIOS",
    authorTr: "EPODONIOS",
    authorRu: "EPODONIOS",
  },
  {
    id: 36,
    fa: "در سکوت کامل، صدای قلب آهنگ اصلی زندگی است.",
    en: "In absolute silence, the heartbeat is life's primary song.",
    tr: "Mutlak sessizlikte kalp atışı hayatın ana şarkısıdır.",
    ru: "В абсолютной тишине сердцебиение — главная песня жизни.",
    ruX: "В абсолютной тишине сердцебиение — главная песня жизни.",
    authorFa: "جان کیج",
    authorEn: "John Cage",
    authorTr: "John Cage",
    authorRu: "Джон Кейдж",
  },
  {
    id: 37,
    fa: "یک ترانه خوب می‌تواند تمام روزت را دوباره بسازد.",
    en: "A good song can rebuild your entire day.",
    tr: "İyi bir şarkı tüm gününüzü yeniden inşa edebilir.",
    ru: "Хорошая песня способна пересобрать весь твой день.",
    ruX: "Хорошая песня способна пересобрать весь твой день.",
    authorFa: "EPODONIOS",
    authorEn: "EPODONIOS",
    authorTr: "EPODONIOS",
    authorRu: "EPODONIOS",
  },
  {
    id: 38,
    fa: "موسیقی، ستاره‌های خاموش را در آسمان ذهن روشن می‌کند.",
    en: "Music lights up the unlit stars in the sky of the mind.",
    tr: "Müzik, zihnin gökyüzündeki sönük yıldızları aydınlatır.",
    ru: "Музыка зажигает погасшие звёзды в небе разума.",
    ruX: "Музыка зажигает погасшие звёзды в небе разума.",
    authorFa: "هکتور برلیوز",
    authorEn: "Hector Berlioz",
    authorTr: "Hector Berlioz",
    authorRu: "Гектор Берлиоз",
  },
  {
    id: 39,
    fa: "سفر به بی‌نهایت، تنها با یک هدست و یک آلبوم آغاز می‌شود.",
    en: "A journey to infinity begins with just headphones and an album.",
    tr: "Sonsuzluğa yolculuk sadece bir kulaklık ve bir albümle başlar.",
    ru: "Путь в бесконечность начинается с наушников и альбома.",
    ruX: "Путь в бесконечность начинается с наушников и альбома.",
    authorFa: "EPODONIOS",
    authorEn: "EPODONIOS",
    authorTr: "EPODONIOS",
    authorRu: "EPODONIOS",
  },
  {
    id: 40,
    fa: "هر ساز موسیقی، صدای یک روح آزاد است.",
    en: "Every musical instrument is the voice of a free spirit.",
    tr: "Her müzik enstrümanı özgür bir ruhun sesidir.",
    ru: "Каждый музыкальный инструмент — голос свободного духа.",
    ruX: "Каждый музыкальный инструмент — голос свободного духа.",
    authorFa: "موریس راول",
    authorEn: "Maurice Ravel",
    authorTr: "Maurice Ravel",
    authorRu: "Морис Равель",
  },
  {
    id: 41,
    fa: "شب بدون موسیقی مانند آسمان بدون ستارگان است.",
    en: "Night without music is like a sky without stars.",
    tr: "Müziksiz gece, yıldızsız bir gökyüzü gibidir.",
    ru: "Ночь без музыки — как небо без звёзд.",
    ruX: "Ночь без музыки — как небо без звёзд.",
    authorFa: "EPODONIOS",
    authorEn: "EPODONIOS",
    authorTr: "EPODONIOS",
    authorRu: "EPODONIOS",
  },
  {
    id: 42,
    fa: "موسیقی تنها دارویی است که هیچ عارضه جانبی ندارد.",
    en: "Music is the only medicine that has no side effects.",
    tr: "Müzik, yan etkisi olmayan tek ilaçtır.",
    ru: "Музыка — единственное лекарство без побочных эффектов.",
    ruX: "Музыка — единственное лекарство без побочных эффектов.",
    authorFa: "بلا بارتوک",
    authorEn: "Béla Bartók",
    authorTr: "Béla Bartók",
    authorRu: "Бела Барток",
  },
  {
    id: 43,
    fa: "صداهای سنتزشده، رویای الکترونیکی آینده را به حال می‌آورند.",
    en: "Synthesized sounds bring the electronic dream of the future to the present.",
    tr: "Sentezlenmiş sesler, geleceğin elektronik rüyasını bugüne getirir.",
    ru: "Синтезированные звуки приносят электронную мечту будущего в настоящее.",
    ruX: "Синтезированные звуки приносят электронную мечту будущего в настоящее.",
    authorFa: "ژان میشل ژار",
    authorEn: "Jean-Michel Jarre",
    authorTr: "Jean-Michel Jarre",
    authorRu: "Жан-Мишель Жарр",
  },
  {
    id: 44,
    fa: "در شب‌های دلتنگی، هر نت موسیقی در آغوش می‌گیرد.",
    en: "On lonely nights, every musical note embraces you.",
    tr: "Yalnız gecelerde, her müzik notası size sarılır.",
    ru: "Одинокими ночами каждая нота обнимает тебя.",
    ruX: "Одинокими ночами каждая нота обнимает тебя.",
    authorFa: "EPODONIOS",
    authorEn: "EPODONIOS",
    authorTr: "EPODONIOS",
    authorRu: "EPODONIOS",
  },
  {
    id: 45,
    fa: "موسیقی، شعری است که نیاز به خوانده شدن ندارد.",
    en: "Music is poetry that does not need to be spoken.",
    tr: "Müzik, konuşulmaya ihtiyaç duymayan bir şiirdir.",
    ru: "Музыка — поэзия, которой не нужно быть произнесённой.",
    ruX: "Музыка — поэзия, которой не нужно быть произнесённой.",
    authorFa: "فلیکس مندلسون",
    authorEn: "Felix Mendelssohn",
    authorTr: "Felix Mendelssohn",
    authorRu: "Феликс Мендельсон",
  },
  {
    id: 46,
    fa: "آرامش شب و موسیقی، ترکیبی برای شفای درون است.",
    en: "The calm of night and music are a blend for inner healing.",
    tr: "Gecenin sakinliği ve müzik, içsel iyileşme için bir karışımdır.",
    ru: "Ночной покой и музыка — смесь для внутреннего исцеления.",
    ruX: "Ночной покой и музыка — смесь для внутреннего исцеления.",
    authorFa: "EPODONIOS",
    authorEn: "EPODONIOS",
    authorTr: "EPODONIOS",
    authorRu: "EPODONIOS",
  },
  {
    id: 47,
    fa: "ملودی‌های ماندگار، رویای بیداری بشر بوده‌اند.",
    en: "Timeless melodies have been mankind's waking dream.",
    tr: "Zamansız melodiler, insanlığın uyanık rüyası olmuştur.",
    ru: "Вечные мелодии были сном наяву человечества.",
    ruX: "Вечные мелодии были сном наяву человечества.",
    authorFa: "جوزپه وردی",
    authorEn: "Giuseppe Verdi",
    authorTr: "Giuseppe Verdi",
    authorRu: "Джузеппе Верди",
  },
  {
    id: 48,
    fa: "موسیقی، نبض تپنده کائنات در رگ‌های شماست.",
    en: "Music is the beating pulse of the cosmos in your veins.",
    tr: "Müzik, evrenin damarlarınızdaki atan nabzıdır.",
    ru: "Музыка — бьющийся пульс космоса в твоих венах.",
    ruX: "Музыка — бьющийся пульс космоса в твоих венах.",
    authorFa: "EPODONIOS",
    authorEn: "EPODONIOS",
    authorTr: "EPODONIOS",
    authorRu: "EPODONIOS",
  },
  {
    id: 49,
    fa: "هر آهنگ یک پرواز بدون نیاز به بال است.",
    en: "Every song is a flight without the need for wings.",
    tr: "Her şarkı, kanatlara ihtiyaç duymayan bir uçuştur.",
    ru: "Каждая песня — полёт, не требующий крыльев.",
    ruX: "Каждая песня — полёт, не требующий крыльев.",
    authorFa: "ریچارد واگنر",
    authorEn: "Richard Wagner",
    authorTr: "Richard Wagner",
    authorRu: "Рихард Вагнер",
  },
  {
    id: 50,
    fa: "سکوت شب، زیباترین استودیو برای شنیدن اصالت صداست.",
    en: "The silence of night is the finest studio to hear pure sound.",
    tr: "Gecenin sessizliği, saf sesi duymak için en iyi stüdyodur.",
    ru: "Тишина ночи — совершеннейшая студия, чтобы услышать чистый звук.",
    ruX: "Тишина ночи — совершеннейшая студия, чтобы услышать чистый звук.",
    authorFa: "EPODONIOS",
    authorEn: "EPODONIOS",
    authorTr: "EPODONIOS",
    authorRu: "EPODONIOS",
  },
];

// Generate exactly 1,000 inspiring music and night quotes by programmatic synthesis of atmospheric themes
const THEME_MATRICES = [
  {
    fa: "وقتی نت‌های {X} در فضا طنین می‌اندازد، {Y} معنایی نو می‌گیرد.",
    en: "When the notes of {X} resound through space, {Y} takes on a new meaning.",
    tr: "{X} notaları uzayda yankıladığında, {Y} yepyeni bir anlam kazanır.",
    // RU templates keep {X}/{Y} in the nominative (coordinated subjects) so any
    // subject pair stays grammatical — Task 40-i18n-ru.
    ru: "{X} и {Y} обретают новый смысл, когда их слышит ночь.",
  },
  {
    fa: "در ژرفای {X}، می‌توان آواز مقدس {Y} را به وضوح شنید.",
    en: "In the depths of {X}, one can clearly hear the sacred hymn of {Y}.",
    tr: "{X} derinliklerinde, {Y}'nin kutsal ilahisi net bir şekilde duyulur.",
    ru: "{X} и {Y} — вот что отчётливо слышно в глубине ночи.",
  },
  {
    fa: "هیچ نیرویی همچون {X} قادر نیست {Y} را به آرامش دعوت کند.",
    en: "No force quite like {X} is capable of inviting {Y} into serene tranquility.",
    tr: "{X} gibi hiçbir güç, {Y}'yi huzurlu bir sükunete davet etmeye kadir değildir.",
    ru: "{X} и {Y} не нуждаются в силе — их покой приходит сам.",
  },
  {
    fa: "{X} پلی است نامرئی که بی‌واسطه ما را به {Y} پیوند می‌زند.",
    en: "{X} is an invisible bridge uniting us seamlessly with {Y}.",
    tr: "{X}, bizi pürüzsüzce {Y} ile birleştiren görünmez bir köprüdür.",
    ru: "{X} и {Y} — невидимый мост между сердцем и ночью.",
  },
  {
    fa: "با شنیدن هر ملودی، احساس می‌کنی که {X} همزاد حقیقی {Y} است.",
    en: "With every heard melody, you realize that {X} is the true soulmate of {Y}.",
    tr: "Duyduğun her melodiyle, {X}'nin {Y}'nin gerçek ruh ikizi olduğunu fark edersin.",
    ru: "С каждой мелодией {X} и {Y} становятся ближе друг к другу.",
  },
  {
    fa: "آن زمان که جهان در خواب است، {X} زمزمه امید و {Y} در قلب شماست.",
    en: "When the sleeping world fades away, {X} becomes a whisper of hope and {Y} in your heart.",
    tr: "Uyuyan dünya geride kaldığında, {X} kalbinde umut ve {Y}'nin bir fısıltısı olur.",
    ru: "Пока мир спит, {X} и {Y} шепчут вашему сердцу о главном.",
  },
  {
    fa: "{X} در سکوت نیمه‌شب، پنجره‌ای گشوده رو به {Y} است.",
    en: "{X} in midnight silence opens a shining gateway toward {Y}.",
    tr: "Gece yarısı sessizliğindeki {X}, {Y}'ye doğru açılan parlak bir kapıdır.",
    ru: "{X} и {Y} — окно, распахнутое в полночь.",
  },
  {
    fa: "هر تپش از {X}، قطره‌ای از شفای ناب بر پهنه {Y} است.",
    en: "Every single pulse of {X} falls like pure healing upon the expanse of {Y}.",
    tr: "{X}'in her bir nabzı, {Y}'nin genişliğine saf bir şifa gibi düşer.",
    ru: "{X} и {Y} падают на душу каплями чистого исцеления.",
  },
  {
    fa: "راز ماندگاری روح، غوطه‌ور شدن در {X} و لمس بی‌واسطه {Y} است.",
    en: "The secret of soul endurance lies in immersing in {X} and directly embracing {Y}.",
    tr: "Ruhun dayanıklılığının sırrı, {X}'e dalmak ve {Y}'yi doğrudan kucaklamaktır.",
    ru: "{X} и {Y} — секрет души, которая не стареет.",
  },
  {
    fa: "آواز شبانه، یادآور این حقیقت است که {X} سرچشمه ابدی {Y} است.",
    en: "The nocturnal song reminds us that {X} is the infinite spring of {Y}.",
    tr: "Gece müziği, {X}'in {Y}'nin sonsuz kaynağı olduğunu hatırlatır.",
    ru: "Ночная песня помнит: {X} и {Y} — неиссякаемый источник.",
  },
];

const SUBJECT_PAIRS = [
  { faX: "موسیقی اصیل", faY: "شب‌های پر ستاره", enX: "pure music", enY: "starless nights", trX: "saf müzik", trY: "yıldızsız geceler", ruX: "чистая музыка", ruY: "беззвёздные ночи", auth: "EPODONIOS" },
  { faX: "ریتم کیهانی", faY: "آرامش درون", enX: "cosmic rhythm", enY: "inner peace", trX: "kozmik ritim", trY: "iç huzur", ruX: "космический ритм", ruY: "внутренний покой", auth: "NOBODY ARCHIVE" },
  { faX: "سکوت میان نت‌ها", faY: "ابدیت زمان", enX: "the silence between notes", enY: "eternal time", trX: "notalar arası sessizlik", trY: "sonsuz zaman", ruX: "тишина между нотами", ruY: "вечное время", auth: "Claude Debussy" },
  { faX: "ملودی‌های سینمایی", faY: "رویاهای فراموش‌شده", enX: "cinematic melodies", enY: "forgotten dreams", trX: "sinematik melodiler", trY: "unutulmuş rüyalar", ruX: "кинематографичные мелодии", ruY: "забытые сны", auth: "Hans Zimmer" },
  { faX: "امواج فرکانس", faY: "دریاچه‌های خیال", enX: "waves of frequency", enY: "lakes of imagination", trX: "frekans dalgaları", trY: "hayal gölleri", ruX: "волны частот", ruY: "озёра воображения", auth: "EPODONIOS" },
  { faX: "ترانه‌های ماندگار", faY: "خاطرات دورانی که گذشت", enX: "timeless songs", enY: "memories of a bygone era", trX: "zamansız şarkılar", trY: "geçmiş zamanın anıları", ruX: "вечные песни", ruY: "воспоминания ушедшей эпохи", auth: "Ennio Morricone" },
  { faX: "نوای الکترونیک", faY: "آนาکردی افکار", enX: "electronic synthesizer glow", enY: "the tapestry of thought", trX: "elektronik sentezleyici ışıltısı", trY: "düşünce dokusu", ruX: "электронное сияние синтезатора", ruY: "ткань мыслей", auth: "Jean-Michel Jarre" },
  { faX: "یک آکورد دلنشین", faY: "التیام زخم‌های روزمره", enX: "a resonant chord", enY: "the healing of daily toil", trX: "yankılanan bir akor", trY: "günlük yorgunluğun şifası", ruX: "звенящий аккорд", ruY: "исцеление дневной усталости", auth: "Ryuichi Sakamoto" },
  { faX: "صداهای شبانه", faY: "نور ستاره‌های دوردست", enX: "nocturnal vibrations", enY: "light of distant stars", trX: "gece titreşimleri", trY: "uzak yıldızların ışığı", ruX: "ночные вибрации", ruY: "свет далёких звёзд", auth: "Vangelis" },
  { faX: "طنین پیانو در تاریکی", faY: "لطافت روح انسان", enX: "piano echoes in the dark", enY: "the human soul's tenderness", trX: "karanlıkta piyano yankıları", trY: "insan ruhunun nezaketi", ruX: "отголоски фортепиано в темноте", ruY: "нежность человеческой души", auth: "Frédéric Chopin" },
  { faX: "آهنگ‌های Nobody", faY: "پرواز در بی‌نهایت", enX: "Nobody symphonies", enY: "flight into infinity", trX: "Nobody senfonileri", trY: "sonsuzluğa uçuş", ruX: "симфонии NOBODY", ruY: "полёт в бесконечность", auth: "EPODONIOS" },
  { faX: "لرزش تارها", faY: "حقیقت ناگفته عشق", enX: "quivering strings", enY: "the unspoken truth of love", trX: "titreyen teller", trY: "aşkın söylenmemiş gerçeği", ruX: "дрожащие струны", ruY: "невысказанная правда любви", auth: "Antonio Vivaldi" },
  { faX: "هماهنگی اصوات", faY: "نظم کیهانی ستارگان", enX: "harmony of sounds", enY: "the celestial order of stars", trX: "seslerin uyumu", trY: "yıldızların göksel düzeni", ruX: "гармония звуков", ruY: "небесный порядок звёзд", auth: "Johannes Brahms" },
  { faX: "پژواک باس عمیق", faY: "ضربان زمین در نیمه‌شب", enX: "deep bass resonances", enY: "midnight pulse of the earth", trX: "derin bas yankıları", trY: "dünyanın gece yarısı nabzı", ruX: "глубокие басы", ruY: "полночный пульс Земли", auth: "EPODONIOS" },
  { faX: "نوای ساز", faY: "بیداری روحی رها", enX: "acoustic timbre", enY: "the awakening of a liberated spirit", trX: "akustik tınlama", trY: "özgür bir ruhun uyanışı", ruX: "акустический тембр", ruY: "пробуждение свободного духа", auth: "Maurice Ravel" },
];

export const MUSIC_QUOTES: QuoteItem[] = [...BASE_QUOTES];

// Automatically generate up to 1,000 unique quotes
let idCounter = MUSIC_QUOTES.length + 1;
while (MUSIC_QUOTES.length < 1000) {
  const matrixIdx = (idCounter - 51) % THEME_MATRICES.length;
  const pairIdx = Math.floor((idCounter - 51) / THEME_MATRICES.length) % SUBJECT_PAIRS.length;
  const variation = Math.floor((idCounter - 51) / (THEME_MATRICES.length * SUBJECT_PAIRS.length));

  const mat = THEME_MATRICES[matrixIdx];
  const pair = SUBJECT_PAIRS[pairIdx];

  const faText = mat.fa.replace("{X}", pair.faX).replace("{Y}", pair.faY);
  const enText = mat.en.replace("{X}", pair.enX).replace("{Y}", pair.enY);
  const trText = mat.tr.replace("{X}", pair.trX).replace("{Y}", pair.trY);
  // RU: fall back to the English subject words when a pair has no ruX/ruY, so
  // a generated ru quote degrades gracefully to en — Task 40-i18n-ru.
  const ruText = mat.ru.replace("{X}", pair.ruX ?? pair.enX).replace("{Y}", pair.ruY ?? pair.enY);

  MUSIC_QUOTES.push({
    id: idCounter,
    fa: variation === 0 ? faText : `${faText} • (تأمل شبانه ${idCounter})`,
    en: variation === 0 ? enText : `${enText} • (Nocturnal Meditation ${idCounter})`,
    tr: variation === 0 ? trText : `${trText} • (Gece Tefekkürü ${idCounter})`,
    ru: variation === 0 ? ruText : `${ruText} • (Ночная медитация ${idCounter})`,
    ruX: variation === 0 ? ruText : `${ruText} • (Ночная медитация ${idCounter})`,
    authorFa: pair.auth,
    authorEn: pair.auth,
    authorTr: pair.auth,
    authorRu: pair.auth,
  });
  idCounter++;
}

// Utility to get a consistent quote for a given track or index
export function getTrackQuote(trackIndex: number): QuoteItem {
  return MUSIC_QUOTES[trackIndex % MUSIC_QUOTES.length] || MUSIC_QUOTES[0];
}
